tap "botantony/terraria-server", "https://github.com/botantony/homebrew-terraria-server.git"
tap "ctdk/ctdk"
tap "felixkratz/formulae"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/test-bot"
tap "koekeishiya/formulae"
brew "gettext"
brew "readline"
brew "shellcheck"
brew "actionlint"
brew "ad"
brew "xz"
brew "zstd"
brew "jpeg-xl"
brew "aom"
brew "openssl@3"
brew "sqlite"
brew "python@3.12"
brew "icu4c@76"
brew "python@3.13"
brew "openjdk"
brew "apktool"
brew "apr"
brew "apr-util"
brew "argon2"
brew "aria2"
brew "ruby"
brew "asciidoctor"
brew "asciinema"
brew "aspell"
brew "dbus"
brew "autoconf"
brew "autoconf-archive"
brew "automake"
brew "bacon"
brew "bat"
brew "bison"
brew "bitrise"
brew "btop"
brew "ghc"
brew "cabal-install"
brew "capstone"
brew "catgirl"
brew "ccache"
brew "clang-format"
brew "cling"
brew "cmake"
brew "cmatrix"
brew "cmocka"
brew "codeberg-cli"
brew "colima"
brew "libtool"
brew "krb5"
brew "php"
brew "composer"
brew "coreutils"
brew "cowsay"
brew "dart-sdk"
brew "dotnet"
brew "exiftool"
brew "facad"
brew "openjpeg"
brew "leptonica"
brew "tesseract"
brew "mupdf"
brew "fancy-cat"
brew "fastfetch"
brew "libevent"
brew "libtasn1"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "libass"
brew "srt"
brew "ffmpeg"
brew "figlet"
brew "fortune"
brew "fselect"
brew "fzf"
brew "gh"
brew "gifsicle"
brew "git"
brew "glew"
brew "gnu-tar"
brew "gnupg"
brew "go"
brew "grep"
brew "gtk+3"
brew "gtk-mac-integration"
brew "haskell-stack"
brew "pkgconf"
brew "hdf5"
brew "help2man"
brew "httpd"
brew "icarus-verilog"
brew "jadx"
brew "jq"
brew "json-glib"
brew "kotlin"
brew "lazygit"
brew "lbdb"
brew "libmagic"
brew "libxml2"
brew "lmdb"
brew "lorem"
brew "lsd"
brew "luarocks"
brew "lynx"
brew "mariadb"
brew "mas"
brew "maven"
brew "ninja"
brew "meson"
brew "mpv"
brew "nasm"
brew "ncmdump"
brew "tree-sitter"
brew "neovim"
brew "ninvaders"
brew "node"
brew "opam"
brew "openvino"
brew "p7zip"
brew "pinentry-mac"
brew "pipx"
brew "popt"
brew "qt"
brew "redis"
brew "rename"
brew "ripgrep"
brew "rust"
brew "rustup"
brew "sdl3"
brew "shfmt"
brew "simdutf"
brew "sl"
brew "snort"
brew "speedtest-cli"
brew "stow"
brew "talloc"
brew "tdb"
brew "tealdeer"
brew "tevent"
brew "texinfo"
brew "tmux"
brew "tree"
brew "umka-lang"
brew "uv"
brew "vifm"
brew "vim"
brew "wget"
brew "yaz"
brew "yazi"
brew "yices2"
brew "zig"
brew "zlib"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "botantony/terraria-server/terraria-server"
brew "botantony/terraria-server/terraria-server@1.4.2.3"
brew "botantony/terraria-server/terraria-server@1.4.3.6"
brew "felixkratz/formulae/borders"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
cask "amneziavpn"
cask "brave-browser"
cask "cool-retro-term"
cask "crystalfetch"
cask "discord"
cask "font-fira-code"
cask "font-gohufont-nerd-font"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "git-credential-manager"
cask "google-chrome"
cask "gstreamer-runtime"
cask "iina"
cask "kitty"
cask "obsidian"
cask "powershell"
cask "spaceid"
cask "telegram"
cask "utm"
cask "virtualbox"
cask "virtualbuddy"
cask "wine-stable"
cask "xquartz"
mas "AdGuard for Safari", id: 1440147259
mas "Bluebook Exams", id: 1645016851
mas "DEATH STRANDING DIRECTOR'S CUT", id: 6449748961
mas "DevCleaner", id: 1388020431
mas "Developer", id: 640199958
mas "ExifTool Reader", id: 1636199770
mas "GarageBand", id: 682658836
mas "Hex Fiend", id: 1342896380
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Mactracker", id: 430255202
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Twitter", id: 1482454543
mas "Userscripts-Mac-App", id: 1463298887
mas "Xcode", id: 497799835
