tap "botantony/terraria-server", "https://github.com/botantony/homebrew-terraria-server.git"
tap "felixkratz/formulae"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/test-bot"
tap "koekeishiya/formulae"
brew "gettext"
brew "readline"
brew "shellcheck"
brew "xz"
brew "glib"
brew "openssl@3"
brew "sqlite"
brew "python@3.13"
brew "openjdk"
brew "apktool"
brew "ruby"
brew "asciidoctor"
brew "asciinema"
brew "autoconf"
brew "automake"
brew "bison"
brew "btop"
brew "cling"
brew "cmake"
brew "codeberg-cli"
brew "lima"
brew "colima"
brew "libtool"
brew "krb5"
brew "php"
brew "coreutils"
brew "libevent"
brew "pkgconf"
brew "docker"
brew "dotnet"
brew "mupdf"
brew "fancy-cat"
brew "fastfetch"
brew "python@3.12"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "ghc"
brew "ghcup"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "go"
brew "grep"
brew "haskell-stack"
brew "icarus-verilog"
brew "jq"
brew "just"
brew "kotlin"
brew "lazygit"
brew "lorem"
brew "luarocks"
brew "lynx"
brew "mas"
brew "maven"
brew "ninja"
brew "meson"
brew "mpv"
brew "tree-sitter"
brew "neovim"
brew "node"
brew "opam"
brew "pinentry-mac"
brew "pipx"
brew "qt"
brew "ripgrep"
brew "rust"
brew "rustup"
brew "speedtest-cli"
brew "stow"
brew "texlive"
brew "tmux"
brew "tree"
brew "umka-lang"
brew "uv"
brew "vim"
brew "wget"
brew "yazi"
brew "zig"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "botantony/terraria-server/terraria-server"
brew "felixkratz/formulae/borders"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
cask "brave-browser"
cask "cool-retro-term"
cask "crystalfetch"
cask "discord"
cask "font-fira-code"
cask "font-gohufont-nerd-font"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "git-credential-manager"
cask "google-chrome"
cask "gstreamer-runtime"
cask "iina"
cask "kitty"
cask "microsoft-auto-update"
cask "microsoft-teams"
cask "obsidian"
cask "orion"
cask "powershell"
cask "qutebrowser"
cask "spaceid"
cask "telegram"
cask "telegram-desktop"
cask "utm"
cask "virtualbox"
cask "virtualbuddy"
cask "wine-stable"
cask "xquartz"
cask "zerotier-one"
mas "AdGuard for Safari", id: 1440147259
mas "Bluebook", id: 1645016851
mas "DeathStranding", id: 6449748961
mas "DevCleaner", id: 1388020431
mas "Developer", id: 640199958
mas "ExifTool Reader", id: 1636199770
mas "GarageBand", id: 682658836
mas "Hex Fiend", id: 1342896380
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Mactracker", id: 430255202
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Twitter", id: 1482454543
mas "Userscripts", id: 1463298887
mas "Xcode", id: 497799835
