# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#ffdd33" }

# Hovered
hovered         = { fg = "#181818", bg = "#ffdd33" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#73d936", italic = true }
find_position = { fg = "#ffdd33", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#73d936", bg = "#73d936" }
marker_copied   = { fg = "#73d936", bg = "#73d936" }
marker_cut      = { fg = "#f43841", bg = "#f43841" }

# Tab
tab_active   = { fg = "#181818", bg = "#52494e" }
tab_inactive = { fg = "#e4e4e4", bg = "#453d41" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "#565f73" }

# Highlighting

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#453d41", bg = "#453d41" }


# Progress
progress_label  = { fg = "#f5f5f5", bold = true }
progress_normal = { fg = "#52494e", bg = "#453d41" }
progress_error  = { fg = "#f43841", bg = "#453d41" }

# Permissions
permissions_t = { fg = "#52494e" }
permissions_r = { fg = "#73d936" }
permissions_w = { fg = "#f43841" }
permissions_x = { fg = "#73d936" }
permissions_s = { fg = "#565f73" }

# : }}}


# : mode {{{

[mode]
normal_main = { fg = "#181818", bg = "#e4e4e4", bold = true }
normal_alt = { fg = "#181818", bg = "#e4e4e4", bold = true }

select_main = { fg = "#181818", bg = "#73d936", bold = true }
select_alt = { fg = "#181818", bg = "#73d936", bold = true }

unset_main  = { fg = "#181818", bg = "#9e95c7", bold = true }
unset_alt  = { fg = "#181818", bg = "#9e95c7", bold = true }

# : }}}


# : Input {{{

[input]
border   = { fg = "#95a99f" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border   = { fg = "#52494e" }
active   = { fg = "#ffdd33" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#52494e" }
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#453d41" }
cand            = { fg = "#ffdd33" }
rest            = { fg = "#565f73" }
desc            = { fg = "#ffdd33" }
separator       = "  "
separator_style = { fg = "#52494e" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#ffdd33" }
exec    = { fg = "#ffdd33" }
desc    = { fg = "#565f73" }
hovered = { bg = "#52494e", bold = true }
footer  = { fg = "#453d41", bg = "#e4e4e4" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#ffdd33" },

    # Videos
    { mime = "video/*", fg = "#73d936" },
    { mime = "audio/*", fg = "#73d936" },

    # Archives
    { mime = "application/zip",             fg = "#ffdd33" },
    { mime = "application/gzip",            fg = "#ffdd33" },
    { mime = "application/x-tar",           fg = "#ffdd33" },
    { mime = "application/x-bzip",          fg = "#ffdd33" },
    { mime = "application/x-bzip2",         fg = "#ffdd33" },
    { mime = "application/x-7z-compressed", fg = "#ffdd33" },
    { mime = "application/x-rar",           fg = "#ffdd33" },

    # Fallback
    { name = "*", fg = "#e4e4e4" },
    { name = "*/", fg = "#ffdd33" }
]

# : }}}
