[mgr]
show_hidden = true
sort_sensitive = true
linemode = "size_and_mtime"

[opener]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
]
play = [
	{ run = 'open "$@"', orphan = true, for = 'macos' },
]
open = [
	{ run = 'open "$@"', desc = "Open", for = 'macos' },
]
